sonar.organization=DUUY69
sonar.projectKey=DUUY69_PRM_Lab2
sonar.projectName=PRM Lab2

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.g.dart,**/.dart_tool/**,**/build/**,android/**,ios/**,linux/**,macos/**,windows/**,web/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
