sonar.projectKey=hdant2_PRM393_Lab3_SE182125
sonar.organization=hdant2

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.g.dart,**/.dart_tool/**,**/build/**,android/**,ios/**,linux/**,macos/**,windows/**,web/**

sonar.coverage.exclusions=**/screens/**,**/main.dart

sonar.cpd.exclusions=**/screens/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
