// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYScbCaMWG9pV8rV4_tw-106McSlfi-Pc',
    appId: '1:243614851294:web:2a3f401a87b5dc7f6e224f',
    messagingSenderId: '243614851294',
    projectId: 'prm392-lab3',
    authDomain: 'prm392-lab3.firebaseapp.com',
    storageBucket: 'prm392-lab3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcynRBgyB1pOHRfD5N4NKLKfbZ8RTVF0',
    appId: '1:243614851294:android:43e315583e2735766e224f',
    messagingSenderId: '243614851294',
    projectId: 'prm392-lab3',
    storageBucket: 'prm392-lab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ONRjlFSbq7KKQC9r4A1eYSa3o7-R7Nk',
    appId: '1:243614851294:ios:65f56b497b03f56d6e224f',
    messagingSenderId: '243614851294',
    projectId: 'prm392-lab3',
    storageBucket: 'prm392-lab3.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ONRjlFSbq7KKQC9r4A1eYSa3o7-R7Nk',
    appId: '1:243614851294:ios:65f56b497b03f56d6e224f',
    messagingSenderId: '243614851294',
    projectId: 'prm392-lab3',
    storageBucket: 'prm392-lab3.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYScbCaMWG9pV8rV4_tw-106McSlfi-Pc',
    appId: '1:243614851294:web:b13879179d2ef1916e224f',
    messagingSenderId: '243614851294',
    projectId: 'prm392-lab3',
    authDomain: 'prm392-lab3.firebaseapp.com',
    storageBucket: 'prm392-lab3.firebasestorage.app',
  );
}
